const playerPoolData = {
  PPR: 1,
  DraftRankings: [
    {
      playerId: "259",
      position: "RB",
      displayName: "Adrian Peterson",
      fname: "Adrian",
      lname: "Peterson",
      team: "MIN",
      byeWeek: "5",
      nerdRank: "1.826",
      positionRank: "1",
      overallRank: "1"
    },
    {
      playerId: "1981",
      position: "RB",
      displayName: "Doug Martin",
      fname: "Doug",
      lname: "Martin",
      team: "TB",
      byeWeek: "5",
      nerdRank: "2.635",
      positionRank: "2",
      overallRank: "2"
    },
    {
      playerId: "145",
      position: "RB",
      displayName: "Jamaal Charles",
      fname: "Jamaal",
      lname: "Charles",
      team: "KC",
      byeWeek: "10",
      nerdRank: "5.594",
      positionRank: "3",
      overallRank: "3"
    },
    {
      playerId: "454",
      position: "WR",
      displayName: "Calvin Johnson",
      fname: "Calvin",
      lname: "Johnson",
      team: "DET",
      byeWeek: "9",
      nerdRank: "7.209",
      positionRank: "1",
      overallRank: "4"
    },
    {
      playerId: "1136",
      position: "RB",
      displayName: "C.J. Spiller",
      fname: "C.J.",
      lname: "Spiller",
      team: "BUF",
      byeWeek: "12",
      nerdRank: "6.140",
      positionRank: "4",
      overallRank: "5"
    },
    {
      playerId: "810",
      position: "RB",
      displayName: "LeSean McCoy",
      fname: "LeSean",
      lname: "McCoy",
      team: "PHI",
      byeWeek: "12",
      nerdRank: "6.840",
      positionRank: "5",
      overallRank: "6"
    },
    {
      playerId: "269",
      position: "RB",
      displayName: "Ray Rice",
      fname: "Ray",
      lname: "Rice",
      team: "BAL",
      byeWeek: "8",
      nerdRank: "9.681",
      positionRank: "6",
      overallRank: "7"
    },
    {
      playerId: "1879",
      position: "RB",
      displayName: "Trent Richardson",
      fname: "Trent",
      lname: "Richardson",
      team: "CLE",
      byeWeek: "10",
      nerdRank: "6.810",
      positionRank: "7",
      overallRank: "8"
    },
    {
      playerId: "917",
      position: "RB",
      displayName: "Arian Foster",
      fname: "Arian",
      lname: "Foster",
      team: "HOU",
      byeWeek: "8",
      nerdRank: "6.564",
      positionRank: "8",
      overallRank: "9"
    },
    {
      playerId: "1143",
      position: "WR",
      displayName: "Dez Bryant",
      fname: "Dez",
      lname: "Bryant",
      team: "DAL",
      byeWeek: "11",
      nerdRank: "14.809",
      positionRank: "2",
      overallRank: "10"
    },
    {
      playerId: "480",
      position: "WR",
      displayName: "Brandon Marshall",
      fname: "Brandon",
      lname: "Marshall",
      team: "CHI",
      byeWeek: "8",
      nerdRank: "23.576",
      positionRank: "3",
      overallRank: "11"
    },
    {
      playerId: "1441",
      position: "WR",
      displayName: "A.J. Green",
      fname: "A.J.",
      lname: "Green",
      team: "CIN",
      byeWeek: "12",
      nerdRank: "15.426",
      positionRank: "4",
      overallRank: "12"
    },
    {
      playerId: "175",
      position: "RB",
      displayName: "Matt Forte",
      fname: "Matt",
      lname: "Forte",
      team: "CHI",
      byeWeek: "8",
      nerdRank: "17.520",
      positionRank: "9",
      overallRank: "13"
    },
    {
      playerId: "1172",
      position: "WR",
      displayName: "Demaryius Thomas",
      fname: "Demaryius",
      lname: "Thomas",
      team: "DEN",
      byeWeek: "9",
      nerdRank: "24.444",
      positionRank: "5",
      overallRank: "14"
    },
    {
      playerId: "1446",
      position: "WR",
      displayName: "Julio Jones",
      fname: "Julio",
      lname: "Jones",
      team: "ATL",
      byeWeek: "6",
      nerdRank: "19.617",
      positionRank: "6",
      overallRank: "15"
    },
    {
      playerId: "230",
      position: "RB",
      displayName: "Marshawn Lynch",
      fname: "Marshawn",
      lname: "Lynch",
      team: "SEA",
      byeWeek: "12",
      nerdRank: "8.674",
      positionRank: "10",
      overallRank: "16"
    },
    {
      playerId: "1187",
      position: "TE",
      displayName: "Jimmy Graham",
      fname: "Jimmy",
      lname: "Graham",
      team: "NO",
      byeWeek: "7",
      nerdRank: "19.511",
      positionRank: "1",
      overallRank: "17"
    },
    {
      playerId: "452",
      position: "WR",
      displayName: "Andre Johnson",
      fname: "Andre",
      lname: "Johnson",
      team: "HOU",
      byeWeek: "8",
      nerdRank: "36.538",
      positionRank: "7",
      overallRank: "18"
    },
    {
      playerId: "394",
      position: "WR",
      displayName: "Larry Fitzgerald",
      fname: "Larry",
      lname: "Fitzgerald",
      team: "ARI",
      byeWeek: "9",
      nerdRank: "31.072",
      positionRank: "8",
      overallRank: "19"
    },
    {
      playerId: "14",
      position: "QB",
      displayName: "Drew Brees",
      fname: "Drew",
      lname: "Brees",
      team: "NO",
      byeWeek: "7",
      nerdRank: "13.222",
      positionRank: "1",
      overallRank: "20"
    },
    {
      playerId: "578",
      position: "WR",
      displayName: "Roddy White",
      fname: "Roddy",
      lname: "White",
      team: "ATL",
      byeWeek: "6",
      nerdRank: "33.847",
      positionRank: "9",
      overallRank: "21"
    },
    {
      playerId: "87",
      position: "QB",
      displayName: "Aaron Rodgers",
      fname: "Aaron",
      lname: "Rodgers",
      team: "GB",
      byeWeek: "4",
      nerdRank: "14.596",
      positionRank: "2",
      overallRank: "22"
    },
    {
      playerId: "285",
      position: "RB",
      displayName: "Darren Sproles",
      fname: "Darren",
      lname: "Sproles",
      team: "NO",
      byeWeek: "7",
      nerdRank: "52.109",
      positionRank: "11",
      overallRank: "23"
    },
    {
      playerId: "1437",
      position: "WR",
      displayName: "Randall Cobb",
      fname: "Randall",
      lname: "Cobb",
      team: "GB",
      byeWeek: "4",
      nerdRank: "36.393",
      positionRank: "10",
      overallRank: "24"
    },
    {
      playerId: "205",
      position: "RB",
      displayName: "Steven Jackson",
      fname: "Steven",
      lname: "Jackson",
      team: "ATL",
      byeWeek: "6",
      nerdRank: "21.775",
      positionRank: "12",
      overallRank: "25"
    },
    {
      playerId: "139",
      position: "RB",
      displayName: "Reggie Bush",
      fname: "Reggie",
      lname: "Bush",
      team: "DET",
      byeWeek: "9",
      nerdRank: "34.799",
      positionRank: "13",
      overallRank: "26"
    },
    {
      playerId: "1262",
      position: "WR",
      displayName: "Victor Cruz",
      fname: "Victor",
      lname: "Cruz",
      team: "NYG",
      byeWeek: "9",
      nerdRank: "37.835",
      positionRank: "11",
      overallRank: "27"
    },
    {
      playerId: "1809",
      position: "RB",
      displayName: "Alfred Morris",
      fname: "Alfred",
      lname: "Morris",
      team: "WAS",
      byeWeek: "5",
      nerdRank: "13.898",
      positionRank: "14",
      overallRank: "28"
    },
    {
      playerId: "208",
      position: "RB",
      displayName: "Chris Johnson",
      fname: "Chris",
      lname: "Johnson",
      team: "TEN",
      byeWeek: "8",
      nerdRank: "23.016",
      positionRank: "15",
      overallRank: "29"
    },
    {
      playerId: "573",
      position: "WR",
      displayName: "Reggie Wayne",
      fname: "Reggie",
      lname: "Wayne",
      team: "IND",
      byeWeek: "8",
      nerdRank: "48.439",
      positionRank: "12",
      overallRank: "30"
    },
    {
      playerId: "217",
      position: "RB",
      displayName: "Maurice Jones-Drew",
      fname: "Maurice",
      lname: "Jones-Drew",
      team: "JAC",
      byeWeek: "9",
      nerdRank: "28.204",
      positionRank: "16",
      overallRank: "31"
    },
    {
      playerId: "323",
      position: "WR",
      displayName: "Danny Amendola",
      fname: "Danny",
      lname: "Amendola",
      team: "NE",
      byeWeek: "10",
      nerdRank: "54.265",
      positionRank: "13",
      overallRank: "32"
    },
    {
      playerId: "444",
      position: "WR",
      displayName: "Vincent Jackson",
      fname: "Vincent",
      lname: "Jackson",
      team: "TB",
      byeWeek: "5",
      nerdRank: "38.641",
      positionRank: "14",
      overallRank: "33"
    },
    {
      playerId: "371",
      position: "WR",
      displayName: "Marques Colston",
      fname: "Marques",
      lname: "Colston",
      team: "NO",
      byeWeek: "7",
      nerdRank: "48.866",
      positionRank: "15",
      overallRank: "34"
    },
    {
      playerId: "66",
      position: "QB",
      displayName: "Peyton Manning",
      fname: "Peyton",
      lname: "Manning",
      team: "DEN",
      byeWeek: "9",
      nerdRank: "24.350",
      positionRank: "3",
      overallRank: "35"
    },
    {
      playerId: "343",
      position: "WR",
      displayName: "Dwayne Bowe",
      fname: "Dwayne",
      lname: "Bowe",
      team: "KC",
      byeWeek: "10",
      nerdRank: "46.162",
      positionRank: "16",
      overallRank: "36"
    },
    {
      playerId: "1797",
      position: "RB",
      displayName: "David Wilson",
      fname: "David",
      lname: "Wilson",
      team: "NYG",
      byeWeek: "9",
      nerdRank: "31.348",
      positionRank: "17",
      overallRank: "37"
    },
    {
      playerId: "733",
      position: "TE",
      displayName: "Jason Witten",
      fname: "Jason",
      lname: "Witten",
      team: "DAL",
      byeWeek: "11",
      nerdRank: "50.587",
      positionRank: "2",
      overallRank: "38"
    },
    {
      playerId: "1398",
      position: "QB",
      displayName: "Cam Newton",
      fname: "Cam",
      lname: "Newton",
      team: "CAR",
      byeWeek: "4",
      nerdRank: "31.064",
      positionRank: "4",
      overallRank: "39"
    },
    {
      playerId: "576",
      position: "WR",
      displayName: "Wes Welker",
      fname: "Wes",
      lname: "Welker",
      team: "DEN",
      byeWeek: "9",
      nerdRank: "51.543",
      positionRank: "17",
      overallRank: "40"
    },
    {
      playerId: "1421",
      position: "RB",
      displayName: "DeMarco Murray",
      fname: "DeMarco",
      lname: "Murray",
      team: "DAL",
      byeWeek: "11",
      nerdRank: "35.848",
      positionRank: "18",
      overallRank: "41"
    },
    {
      playerId: "1423",
      position: "RB",
      displayName: "Stevan Ridley",
      fname: "Stevan",
      lname: "Ridley",
      team: "NE",
      byeWeek: "10",
      nerdRank: "23.262",
      positionRank: "19",
      overallRank: "42"
    },
    {
      playerId: "1142",
      position: "WR",
      displayName: "Antonio Brown",
      fname: "Antonio",
      lname: "Brown",
      team: "PIT",
      byeWeek: "5",
      nerdRank: "58.251",
      positionRank: "18",
      overallRank: "43"
    },
    {
      playerId: "235",
      position: "RB",
      displayName: "Darren McFadden",
      fname: "Darren",
      lname: "McFadden",
      team: "OAK",
      byeWeek: "7",
      nerdRank: "47.159",
      positionRank: "20",
      overallRank: "44"
    },
    {
      playerId: "13",
      position: "QB",
      displayName: "Tom Brady",
      fname: "Tom",
      lname: "Brady",
      team: "NE",
      byeWeek: "10",
      nerdRank: "36.116",
      positionRank: "5",
      overallRank: "45"
    },
    {
      playerId: "404",
      position: "WR",
      displayName: "Pierre Garcon",
      fname: "Pierre",
      lname: "Garcon",
      team: "WAS",
      byeWeek: "5",
      nerdRank: "51.719",
      positionRank: "19",
      overallRank: "46"
    },
    {
      playerId: "853",
      position: "WR",
      displayName: "Hakeem Nicks",
      fname: "Hakeem",
      lname: "Nicks",
      team: "NYG",
      byeWeek: "9",
      nerdRank: "57.288",
      positionRank: "20",
      overallRank: "47"
    },
    {
      playerId: "93",
      position: "QB",
      displayName: "Matt Ryan",
      fname: "Matt",
      lname: "Ryan",
      team: "ATL",
      byeWeek: "6",
      nerdRank: "34.626",
      positionRank: "6",
      overallRank: "48"
    },
    {
      playerId: "180",
      position: "RB",
      displayName: "Frank Gore",
      fname: "Frank",
      lname: "Gore",
      team: "SF",
      byeWeek: "9",
      nerdRank: "36.804",
      positionRank: "21",
      overallRank: "49"
    },
    {
      playerId: "1761",
      position: "RB",
      displayName: "Lamar Miller",
      fname: "Lamar",
      lname: "Miller",
      team: "MIA",
      byeWeek: "6",
      nerdRank: "41.932",
      positionRank: "22",
      overallRank: "50"
    },
    {
      playerId: "645",
      position: "TE",
      displayName: "Tony Gonzalez",
      fname: "Tony",
      lname: "Gonzalez",
      team: "ATL",
      byeWeek: "6",
      nerdRank: "50.199",
      positionRank: "3",
      overallRank: "51"
    },
    {
      playerId: "1189",
      position: "TE",
      displayName: "Rob Gronkowski",
      fname: "Rob",
      lname: "Gronkowski",
      team: "NE",
      byeWeek: "10",
      nerdRank: "40.783",
      positionRank: "4",
      overallRank: "52"
    },
    {
      playerId: "541",
      position: "WR",
      displayName: "Steve Smith",
      fname: "Steve",
      lname: "Smith",
      team: "CAR",
      byeWeek: "4",
      nerdRank: "68.382",
      positionRank: "21",
      overallRank: "53"
    },
    {
      playerId: "1146",
      position: "WR",
      displayName: "Eric Decker",
      fname: "Eric",
      lname: "Decker",
      team: "DEN",
      byeWeek: "9",
      nerdRank: "57.276",
      positionRank: "22",
      overallRank: "54"
    }
  ]
};

export default playerPoolData;
